name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main


jobs:
  push_to_huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://osbm:$HF_TOKEN@huggingface.co/datasets/zenodo main